[build]
  publish = "dist"
  command = "npm install && npm run build"

[context.production]
  environment = { NODE_ENV = "production", NPM_FLAGS = "--include=dev" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
